apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: vamsikrishnak123
    provider: github
    repository: angular
  name: vamsikrishnak123-angular
spec:
  description: Imported application for vamsikrishnak123/angular
  httpCloneURL: https://github.com/vamsikrishnak123/angular.git
  org: vamsikrishnak123
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: angular
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/vamsikrishnak123/angular.git
